=== AndresCalimero/corpus-search-auto/src/main/java/perez/garcia/andres/schemas/genres-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="corpus.search.auto" xmlns="corpus.search.auto"
	elementFormDefault="qualified">
	<xs:element name="genres">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="genre" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="corpus" type="xs:string" maxOccurs="unbounded" />
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="corpora" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AndresCalimero/corpus-search-auto/data/corporas/PPCME2/info/genres_mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<genres xmlns="corpus.search.auto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="corpus.search.auto genres-schema.xsd" corpora="PPCME2">
  <genre name="Philosophy">
    <corpus>cmboeth.m3</corpus>
  </genre>
  <genre name="History">
    <corpus>cmbrut3.m3</corpus>
    <corpus>cmcapchr.m4</corpus>
    <corpus>cmgregor.m4</corpus>
    <corpus>cmpeterb.m1</corpus>
    <corpus>cmpolych.m3</corpus>
  </genre>
  <genre name="Travelogue">
    <corpus>cmmandev.m3</corpus>
  </genre>
  <genre name="Bible and Apocrypha">
    <corpus>cmearlps.m2</corpus>
    <corpus>cmntest.m3</corpus>
    <corpus>cmotest.m3</corpus>
  </genre>
  <genre name="Homilies and Sermons">
    <corpus>cmcapser.m4</corpus>
    <corpus>cmfitzja.m4</corpus>
    <corpus>cmgaytry.m34</corpus>
    <corpus>cminnoce.m4</corpus>
    <corpus>cmmirk.m34</corpus>
    <corpus>cmroyal.m34</corpus>
    <corpus>cmwycser.m3</corpus>
	<corpus>cmkentho.m1</corpus>
    <corpus>cmkentse.m2</corpus>
    <corpus>cmlamb1.m1</corpus>
    <corpus>cmlambx1.mx1</corpus>
    <corpus>cmsawles.m1</corpus>
    <corpus>cmtrinit.mx1</corpus>
	<corpus>cmorm.m1</corpus>
  </genre>
  <genre name="Biography and Diaries">
    <corpus>cmedmund.m4</corpus>
    <corpus>cmjulia.m1</corpus>
    <corpus>cmkathe.m1</corpus>
    <corpus>cmmarga.m1</corpus>
  </genre>
  <genre name="Rules, Charters, Wills, Laws, Ecclesiastical Laws and Proceedings-trials">
    <corpus>cmaelr3.m23</corpus>
    <corpus>cmbenrul.m3</corpus>
  </genre>
  <genre name="Medicine, Handbooks, Religious and Educational Treatises">
    <corpus>cmaelr4.m4</corpus>
    <corpus>cmancriw-1.m1</corpus>
    <corpus>cmancriw-2.m1</corpus>
    <corpus>cmayenbi.m2</corpus>
    <corpus>cmcloud.m3</corpus>
    <corpus>cmctpars.m3</corpus>
    <corpus>cmedvern.m3</corpus>
    <corpus>cmhali.m1</corpus>
    <corpus>cmhilton.m34</corpus>
    <corpus>cmjulnor.m34</corpus>
    <corpus>cmkempe.m4</corpus>
    <corpus>cmpurvey.m3</corpus>
    <corpus>cmrollep.m24</corpus>
    <corpus>cmrolltr.m24</corpus>
    <corpus>cmvices1.m1</corpus>
    <corpus>cmvices4.m34</corpus>
	<corpus>cmedthor.m34</corpus>
	<corpus>cmhorses.m3</corpus>
    <corpus>cmthorn.mx4</corpus>
	<corpus>cmreynes.m4</corpus>
  </genre>
  <genre name="Science, Astronomy, Geography">
    <corpus>cmastro.m3</corpus>
    <corpus>cmequato.m3</corpus>
  </genre>
  <genre name="Fiction, Romances, Drama-comedies and Verse">
    <corpus>cmmalory.m4</corpus>
    <corpus>cmsiege.m4</corpus>
	<corpus>cmreynar.m4</corpus>
    <corpus>cmctmeli.m3</corpus>
  </genre>
</genres>

=== AndresCalimero/corpus-search-auto/data/corporas/PPCMBE/info/genres.xml
<?xml version="1.0" encoding="UTF-8"?>
<genres xmlns="corpus.search.auto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="corpus.search.auto genres-schema.xsd" corpora="PPCMBE">
  <genre name="science_other">
    <corpus>albin-1736</corpus>
    <corpus>faraday-1859</corpus>
    <corpus>herschel-1797</corpus>
    <corpus>lyell-1830</corpus>
    <corpus>priestley-1769</corpus>
    <corpus>strutt-1890</corpus>
  </genre>
  <genre name="educ_treatise">
    <corpus>anon-1711</corpus>
    <corpus>bain-1878</corpus>
    <corpus>barclay-1743</corpus>
    <corpus>benson-1908</corpus>
    <corpus>brightland-1711</corpus>
    <corpus>chapman-1774</corpus>
    <corpus>lancaster-1806</corpus>
    <corpus>webster-1718</corpus>
    <corpus>whewell-1837</corpus>
  </genre>
  <genre name="letters_priv">
    <corpus>austen-180x</corpus>
    <corpus>carlyle-1835</corpus>
    <corpus>johnson-1775</corpus>
    <corpus>montagu-1718</corpus>
    <corpus>nightingale-188x</corpus>
    <corpus>nightingale-189x</corpus>
    <corpus>victoria-186x</corpus>
    <corpus>walpole-174x</corpus>
  </genre>
  <genre name="science_medicine">
    <corpus>bardsley-1807</corpus>
    <corpus>lind-1753</corpus>
    <corpus>poore-1876</corpus>
  </genre>
  <genre name="diary">
    <corpus>benson-190x</corpus>
    <corpus>boswell-1776</corpus>
    <corpus>haydon-1808</corpus>
    <corpus>ruskin-1835</corpus>
    <corpus>ryder-1716</corpus>
    <corpus>thring-187x</corpus>
    <corpus>wesley-174x</corpus>
  </genre>
  <genre name="philosophy">
    <corpus>boethja-1897</corpus>
    <corpus>boethri-1785</corpus>
  </genre>
  <genre name="travelogue">
    <corpus>bradley-1905</corpus>
    <corpus>cook-1776</corpus>
    <corpus>cooke-1712</corpus>
    <corpus>montefiore-1836</corpus>
    <corpus>officer-1744</corpus>
    <corpus>reade-1863</corpus>
    <corpus>turner2-1800</corpus>
  </genre>
  <genre name="drama_comedy">
    <corpus>brougham-1861</corpus>
    <corpus>collier-1835</corpus>
    <corpus>colman-1805</corpus>
    <corpus>davys-1716</corpus>
    <corpus>goldsmith-1773</corpus>
    <corpus>stevens-1745</corpus>
    <corpus>wilde-1895</corpus>
  </genre>
  <genre name="sermon">
    <corpus>burton-1762</corpus>
    <corpus>butler-1726</corpus>
    <corpus>froude-1830</corpus>
    <corpus>pusey-186x</corpus>
    <corpus>talbot-1901</corpus>
    <corpus>wollaston-1793</corpus>
  </genre>
  <genre name="history">
    <corpus>carlyle-1837</corpus>
    <corpus>gibbon-1776</corpus>
    <corpus>hind-1707</corpus>
    <corpus>kimber-1742</corpus>
    <corpus>long-1866</corpus>
    <corpus>oman-1895</corpus>
    <corpus>turner1-1799</corpus>
  </genre>
  <genre name="biography_auto">
    <corpus>cibber-1740</corpus>
    <corpus>fayrer-1900</corpus>
    <corpus>okeeffe-1826</corpus>
  </genre>
  <genre name="fiction">
    <corpus>defoe-1719</corpus>
    <corpus>dickens-1837</corpus>
    <corpus>fielding-1749</corpus>
    <corpus>godwin-1805</corpus>
    <corpus>meredith-1895</corpus>
    <corpus>reeve-1777</corpus>
    <corpus>yonge-1865</corpus>
  </genre>
  <genre name="biography_other">
    <corpus>doddridge-1747</corpus>
    <corpus>southey-1813</corpus>
    <corpus>trollope-1882</corpus>
  </genre>
  <genre name="handbook_other">
    <corpus>drummond-1718</corpus>
    <corpus>fleming-1886</corpus>
    <corpus>grafting-1780</corpus>
    <corpus>maxwell-1747</corpus>
    <corpus>skeavington-184x</corpus>
    <corpus>tindall-1814</corpus>
    <corpus>weathers-1913</corpus>
  </genre>
  <genre name="bible">
    <corpus>erv-new-1881</corpus>
    <corpus>erv-old-1885</corpus>
    <corpus>newcome-new-1796</corpus>
    <corpus>purver-new-1764</corpus>
    <corpus>purver-old-1764</corpus>
  </genre>
  <genre name="letters_non-priv">
    <corpus>george-1763</corpus>
    <corpus>gladstone-1873</corpus>
    <corpus>holmes-letters-1749</corpus>
    <corpus>wellesley-1815</corpus>
  </genre>
  <genre name="proceedings_trial">
    <corpus>holmes-trial-1749</corpus>
    <corpus>townley-1746</corpus>
    <corpus>watson-1817</corpus>
  </genre>
  <genre name="law">
    <corpus>statutes-171x</corpus>
    <corpus>statutes-1745</corpus>
    <corpus>statutes-1775</corpus>
    <corpus>statutes-1805</corpus>
    <corpus>statutes-1835</corpus>
    <corpus>statutes-1865</corpus>
    <corpus>statutes-1895</corpus>
  </genre>
</genres>

=== AndresCalimero/corpus-search-auto/CorpusSearch_Auto/data/corporas/YCOE/info/genres.xml
<?xml version="1.0" encoding="UTF-8"?>
<genres xmlns="corpus.search.auto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="corpus.search.auto genres-schema.xsd" corpora="YCOE">
  <genre name="religious treatise">
    <corpus>coadrian.o34</corpus>
    <corpus>coalcuin</corpus>
    <corpus>cocura.o2</corpus>
    <corpus>cocuraC</corpus>
    <corpus>coeluc1</corpus>
    <corpus>coeluc2</corpus>
    <corpus>coleofri.o4</corpus>
    <corpus>colsigef.o3</corpus>
    <corpus>colsigewB</corpus>
    <corpus>colsigewZ.o34</corpus>
    <corpus>colwgeat</corpus>
    <corpus>colwsigeT</corpus>
    <corpus>colwsigeXa.o34</corpus>
    <corpus>colwstan1.o3</corpus>
    <corpus>colwstan2.o3</corpus>
    <corpus>cosolilo</corpus>
    <corpus>cosolsat1.o4</corpus>
    <corpus>cosolsat2</corpus>
  </genre>
  <genre name="homilies">
    <corpus>coaelhom.o3</corpus>
    <corpus>coaugust</corpus>
    <corpus>cocathom1.o3</corpus>
    <corpus>cocathom2.o3</corpus>
    <corpus>coverhomE</corpus>
    <corpus>coverhomL</corpus>
    <corpus>cowulf.o34</corpus>
  </genre>
  <genre name="biography, lives">
    <corpus>coaelive.o3</corpus>
    <corpus>cochad.o24</corpus>
    <corpus>cochristoph</corpus>
    <corpus>coeuphr</corpus>
    <corpus>coeust</corpus>
    <corpus>cogregdC.o24</corpus>
    <corpus>cogregdH.o23</corpus>
    <corpus>cojames</corpus>
    <corpus>comargaC.o34</corpus>
    <corpus>comargaT</corpus>
    <corpus>comart1</corpus>
    <corpus>comart2</corpus>
    <corpus>comart3.o23</corpus>
    <corpus>comary</corpus>
    <corpus>coneot</corpus>
    <corpus>corood</corpus>
    <corpus>cosevensl</corpus>
    <corpus>covinceB</corpus>
  </genre>
  <genre name="travelogue">
    <corpus>coalex.o23</corpus>
  </genre>
  <genre name="fiction">
    <corpus>coapollo.o3</corpus>
  </genre>
  <genre name="history">
    <corpus>cobede.o2</corpus>
    <corpus>cochronA.o23</corpus>
    <corpus>cochronC</corpus>
    <corpus>cochronD</corpus>
    <corpus>cochronE.o34</corpus>
    <corpus>coorosiu.o2</corpus>
  </genre>
  <genre name="rule">
    <corpus>cobenrul.o3</corpus>
    <corpus>cochdrul</corpus>
  </genre>
  <genre name="homs: homilies homu: homilies ls: biography, lives">
    <corpus>coblick.o23</corpus>
    <corpus>coverhom</corpus>
  </genre>
  <genre name="philosophy">
    <corpus>coboeth.o2</corpus>
    <corpus>codicts.o34</corpus>
  </genre>
  <genre name="science">
    <corpus>cobyrhtf.o3</corpus>
  </genre>
  <genre name="ecclesiastical laws">
    <corpus>cocanedgD</corpus>
    <corpus>cocanedgX</corpus>
    <corpus>coinspolD.o34</corpus>
    <corpus>coinspolX</corpus>
  </genre>
  <genre name="charters and wills">
    <corpus>codocu1.o1</corpus>
    <corpus>codocu2.o12</corpus>
    <corpus>codocu2.o2</corpus>
    <corpus>codocu3.o23</corpus>
    <corpus>codocu3.o3</corpus>
    <corpus>codocu4.o24</corpus>
  </genre>
  <genre name="epilogue">
    <corpus>coepigen.o3</corpus>
  </genre>
  <genre name="bible">
    <corpus>coexodusP</corpus>
    <corpus>cogenesiC</corpus>
    <corpus>cootest.o3</corpus>
    <corpus>cowsgosp.o3</corpus>
  </genre>
  <genre name="handbooks, medicine">
    <corpus>coherbar</corpus>
    <corpus>colacnu.o23</corpus>
    <corpus>colaece.o2</corpus>
    <corpus>coquadru.o23</corpus>
  </genre>
  <genre name="laws">
    <corpus>colaw1cn.o3</corpus>
    <corpus>colaw2cn.o3</corpus>
    <corpus>colaw5atr.o3</corpus>
    <corpus>colaw6atr.o3</corpus>
    <corpus>colawaf.o2</corpus>
    <corpus>colawafint.o2</corpus>
    <corpus>colawger.o34</corpus>
    <corpus>colawine.ox2</corpus>
    <corpus>colawnorthu.o3</corpus>
    <corpus>colawwllad.o4</corpus>
  </genre>
  <genre name="geography">
    <corpus>comarvel.o23</corpus>
  </genre>
  <genre name="apocrypha">
    <corpus>conicodA</corpus>
    <corpus>conicodC</corpus>
    <corpus>conicodD</corpus>
    <corpus>conicodE</corpus>
    <corpus>covinsal</corpus>
  </genre>
  <genre name="preface">
    <corpus>coprefcath1.o3</corpus>
    <corpus>coprefcath2.o3</corpus>
    <corpus>coprefcura.o2</corpus>
    <corpus>coprefgen.o3</corpus>
    <corpus>copreflives.o3</corpus>
    <corpus>coprefsolilo</corpus>
  </genre>
  <genre name="science, astronomy">
    <corpus>cotempo.o3</corpus>
  </genre>
</genres>

=== AndresCalimero/corpus-search-auto/CorpusSearch_Auto/data/corporas/YCOE/info/genres_mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<genres xmlns="corpus.search.auto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="corpus.search.auto genres-schema.xsd" corpora="YCOE">
  <genre name="Philosophy">
    <corpus>coboeth.o2</corpus>
    <corpus>codicts.o34</corpus>
  </genre>
  <genre name="History">
    <corpus>cobede.o2</corpus>
    <corpus>cochronA.o23</corpus>
    <corpus>cochronC</corpus>
    <corpus>cochronD</corpus>
    <corpus>cochronE.o34</corpus>
    <corpus>coorosiu.o2</corpus>
  </genre>
  <genre name="Travelogue">
	<corpus>coalex.o23</corpus>
  </genre>
  <genre name="Bible and Apocrypha">
    <corpus>coexodusP</corpus>
    <corpus>cogenesiC</corpus>
    <corpus>cootest.o3</corpus>
    <corpus>cowsgosp.o3</corpus>
	<corpus>conicodA</corpus>
    <corpus>conicodC</corpus>
    <corpus>conicodD</corpus>
    <corpus>conicodE</corpus>
    <corpus>covinsal</corpus>
  </genre>
  <genre name="Homilies and Sermons">
    <corpus>coaelhom.o3</corpus>
    <corpus>coaugust</corpus>
    <corpus>cocathom1.o3</corpus>
    <corpus>cocathom2.o3</corpus>
    <corpus>coverhomE</corpus>
    <corpus>coverhomL</corpus>
    <corpus>cowulf.o34</corpus>
	<corpus>coblick.o23</corpus>
    <corpus>coverhom</corpus>
  </genre>
  <genre name="Biography and Diaries">
    <corpus>coaelive.o3</corpus>
    <corpus>cochad.o24</corpus>
    <corpus>cochristoph</corpus>
    <corpus>coeuphr</corpus>
    <corpus>coeust</corpus>
    <corpus>cogregdC.o24</corpus>
    <corpus>cogregdH.o23</corpus>
    <corpus>cojames</corpus>
    <corpus>comargaC.o34</corpus>
    <corpus>comargaT</corpus>
    <corpus>comart1</corpus>
    <corpus>comart2</corpus>
    <corpus>comart3.o23</corpus>
    <corpus>comary</corpus>
    <corpus>coneot</corpus>
    <corpus>corood</corpus>
    <corpus>cosevensl</corpus>
    <corpus>covinceB</corpus>
  </genre>
  <genre name="Rules, Charters, Wills, Laws, Ecclesiastical Laws and Proceedings-trials">
    <corpus>cobenrul.o3</corpus>
    <corpus>cochdrul</corpus>
	<corpus>cocanedgD</corpus>
    <corpus>cocanedgX</corpus>
    <corpus>coinspolD.o34</corpus>
    <corpus>coinspolX</corpus>
	<corpus>codocu1.o1</corpus>
    <corpus>codocu2.o12</corpus>
    <corpus>codocu2.o2</corpus>
    <corpus>codocu3.o23</corpus>
    <corpus>codocu3.o3</corpus>
    <corpus>codocu4.o24</corpus>
	<corpus>colaw1cn.o3</corpus>
    <corpus>colaw2cn.o3</corpus>
    <corpus>colaw5atr.o3</corpus>
    <corpus>colaw6atr.o3</corpus>
    <corpus>colawaf.o2</corpus>
    <corpus>colawafint.o2</corpus>
    <corpus>colawger.o34</corpus>
    <corpus>colawine.ox2</corpus>
    <corpus>colawnorthu.o3</corpus>
    <corpus>colawwllad.o4</corpus>
  </genre>
  <genre name="Medicine, Handbooks, Religious and Educational Treatises">
    <corpus>coadrian.o34</corpus>
    <corpus>coalcuin</corpus>
    <corpus>cocura.o2</corpus>
    <corpus>cocuraC</corpus>
    <corpus>coeluc1</corpus>
    <corpus>coeluc2</corpus>
    <corpus>coleofri.o4</corpus>
    <corpus>colsigef.o3</corpus>
    <corpus>colsigewB</corpus>
    <corpus>colsigewZ.o34</corpus>
    <corpus>colwgeat</corpus>
    <corpus>colwsigeT</corpus>
    <corpus>colwsigeXa.o34</corpus>
    <corpus>colwstan1.o3</corpus>
    <corpus>colwstan2.o3</corpus>
    <corpus>cosolilo</corpus>
    <corpus>cosolsat1.o4</corpus>
    <corpus>cosolsat2</corpus>
    <corpus>coherbar</corpus>
    <corpus>colacnu.o23</corpus>
    <corpus>colaece.o2</corpus>
    <corpus>coquadru.o23</corpus>
  </genre>
  <genre name="Science, Astronomy, Geography">
    <corpus>cobyrhtf.o3</corpus>
	<corpus>comarvel.o23</corpus>
    <corpus>cotempo.o3</corpus>
  </genre>
  <genre name="Fiction, Romances, Drama-comedies and Verse">
    <corpus>coapollo.o3</corpus>
  </genre>
  <genre name="Prefaces, Epilogues, Non-private and Private letters">
	<corpus>coepigen.o3</corpus>
	<corpus>coprefcath1.o3</corpus>
    <corpus>coprefcath2.o3</corpus>
    <corpus>coprefcura.o2</corpus>
    <corpus>coprefgen.o3</corpus>
    <corpus>copreflives.o3</corpus>
    <corpus>coprefsolilo</corpus>
  </genre>
</genres>

=== AndresCalimero/corpus-search-auto/CorpusSearch_Auto/data/corporas/PPCME2/info/genres.xml
<?xml version="1.0" encoding="UTF-8"?>
<genres xmlns="corpus.search.auto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="corpus.search.auto genres-schema.xsd" corpora="PPCME2">
  <genre name="rule">
    <corpus>cmaelr3.m23</corpus>
    <corpus>cmbenrul.m3</corpus>
  </genre>
  <genre name="relig_treatise">
    <corpus>cmaelr4.m4</corpus>
    <corpus>cmancriw-1.m1</corpus>
    <corpus>cmancriw-2.m1</corpus>
    <corpus>cmayenbi.m2</corpus>
    <corpus>cmcloud.m3</corpus>
    <corpus>cmctpars.m3</corpus>
    <corpus>cmedvern.m3</corpus>
    <corpus>cmhali.m1</corpus>
    <corpus>cmhilton.m34</corpus>
    <corpus>cmjulnor.m34</corpus>
    <corpus>cmkempe.m4</corpus>
    <corpus>cmpurvey.m3</corpus>
    <corpus>cmrollep.m24</corpus>
    <corpus>cmrolltr.m24</corpus>
    <corpus>cmvices1.m1</corpus>
    <corpus>cmvices4.m34</corpus>
  </genre>
  <genre name="handbook_astro">
    <corpus>cmastro.m3</corpus>
    <corpus>cmequato.m3</corpus>
  </genre>
  <genre name="philosophy">
    <corpus>cmboeth.m3</corpus>
  </genre>
  <genre name="history">
    <corpus>cmbrut3.m3</corpus>
    <corpus>cmcapchr.m4</corpus>
    <corpus>cmgregor.m4</corpus>
    <corpus>cmpeterb.m1</corpus>
    <corpus>cmpolych.m3</corpus>
  </genre>
  <genre name="sermon">
    <corpus>cmcapser.m4</corpus>
    <corpus>cmfitzja.m4</corpus>
    <corpus>cmgaytry.m34</corpus>
    <corpus>cminnoce.m4</corpus>
    <corpus>cmmirk.m34</corpus>
    <corpus>cmroyal.m34</corpus>
    <corpus>cmwycser.m3</corpus>
  </genre>
  <genre name="philosophy/fiction">
    <corpus>cmctmeli.m3</corpus>
  </genre>
  <genre name="bible">
    <corpus>cmearlps.m2</corpus>
    <corpus>cmntest.m3</corpus>
    <corpus>cmotest.m3</corpus>
  </genre>
  <genre name="biography_life_of_saint">
    <corpus>cmedmund.m4</corpus>
    <corpus>cmjulia.m1</corpus>
    <corpus>cmkathe.m1</corpus>
    <corpus>cmmarga.m1</corpus>
  </genre>
  <genre name="relig_trreatise">
    <corpus>cmedthor.m34</corpus>
  </genre>
  <genre name="handbook_medicine">
    <corpus>cmhorses.m3</corpus>
    <corpus>cmthorn.mx4</corpus>
  </genre>
  <genre name="homily">
    <corpus>cmkentho.m1</corpus>
    <corpus>cmkentse.m2</corpus>
    <corpus>cmlamb1.m1</corpus>
    <corpus>cmlambx1.mx1</corpus>
    <corpus>cmsawles.m1</corpus>
    <corpus>cmtrinit.mx1</corpus>
  </genre>
  <genre name="romance">
    <corpus>cmmalory.m4</corpus>
    <corpus>cmsiege.m4</corpus>
  </genre>
  <genre name="travelogue">
    <corpus>cmmandev.m3</corpus>
  </genre>
  <genre name="homily_poetry">
    <corpus>cmorm.m1</corpus>
  </genre>
  <genre name="fiction">
    <corpus>cmreynar.m4</corpus>
  </genre>
  <genre name="handbook_other">
    <corpus>cmreynes.m4</corpus>
  </genre>
</genres>
